spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database1.cidtckobgf3m.ap-northeast-2.rds.amazonaws.com/chattest
    username: root
    password: cksdl30104
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  root: info
  #org.hibernate.SQL: debug
